### ISSUE TITLE
No scrolling in support list

### ISSUE THREAD

**Issue by GrayAeon** [Fate-Grand-Automata/FGA#1146]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1664

### Describe the bug

FGA randomly stopped scrolling through the support list yesterday, updated to 1664 and it still doesn't scroll (Also force-stopped it and restarted the phone). After a while it refreshs the support list and after a few refreshes the script stops (Support selection set to Manual). 
If the servant the script is supposed to search shows up at the top, it is selected and the script continues normally (Until it gets stuck in the next support screen).

### Video

[Screenshot, should be enough](https://i.imgur.com/Yoo5klX.png)
(I censored the names and the left Box was added manually, since it pops up shortly after the other 2 and I wasn't able to get them all in one screenshot. Basically the boxes flash alternating (As they are supposed to I think).

### Device model

Honor 8

### Android version

8

**Comment by reconman** [comment]
You're the first person to report this, also behavior changing over night doesn't seem like an issue with FGA but with the phone.

Did anything change on your phone recently? Any changed system settings or updates?

**Comment by GrayAeon** [comment]
No, did not change anything.
I also reinstalled FGA a few days ago, which seems to have fixed the problem.

**Comment by reconman** [comment]
So the problem is solved now?

**Comment by guinibir** [comment]
how did you solve it? im having the same issue now

**Comment by guinibir** [comment]
if anyone runs into same problem - uninstalling and reinstalling fga app solved it for me
if devs wanna try to reproduce issue - i honestly dont kow what caused it, but i was using fga to clear story, with story skip and spam all battle configs, and i kept pausing it when it got to rewarsd and unpausing it when entering new node, and at some point, during camelot story, it bricked like that.

**Comment by leonkevlar** [comment]
Seems that this issue still exists. It also happened to me today. Not sure what caused it but uninstalling and reinstalling the app worked.

**Comment by Kunaki** [comment]
This has been happening to me for a while now. Tried deleting all files and reinstalling and it still wont scroll in support list. Everything else functions and if I scroll manually it will select a support once it sees it. I'm at my wits end. I didnt update my phone or the app, it just broke one day and has not worked since and this has been going on for about a month, maybe a bit less.

build 3048
NA server
Android 14
Samsung S23
