### ISSUE TITLE
Cannot Choose Folder

### ISSUE THREAD

**Issue by Ai-chan** [Fate-Grand-Automata/FGA#1168]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

1669

### Describe the bug

Seems to be an issue similar to #999. Have attempted the following:

- install several different file managers
- with and without root
- enable the External Storage Package (couldn't locate Package Disabler however)

Not sure if the other Redfinger user was able to resolve it on their end so I'm wondering if anyone has any insights.

### Video

N/A

### Device model

Redfinger Cloud Phone (Mi 6X)

### Android version

8

**Comment by reconman** [comment]
Just a guess, the issue was fixed for Samsung by enabling a system app again. Is there an app with the package com.android.externalstorage on your device?

If not, try installing it via https://www.apkmirror.com/apk/google-inc/external-storage-google/. Install the version that fits your Android version (8.0 or 8.1)

**Comment by reconman** [comment]
@kyon1995 Which version did you try? Which Android version do you have?

**Comment by kyon1995** [comment]
> @kyon1995 Which version did you try? Which Android version do you have?

8.1 Singapore server

**Comment by 2312946794** [comment]
我的情况与他相同，唯一的区别是我的系统版本是安卓10，我尝试了你提供的系统文件管理器安装，但是显示安装未完成。我尝试了1826的旧版本，依旧会在选择文件夹这一步闪退。我个人认为这是因为云手机的文件管理器可能存在问题。希望你能给出新的解决思路

**Comment by 2312946794** [comment]
My situation is similar to his, with the only difference being that my system version is Android 10. I tried installing the system file manager you provided, but it showed that the installation was not completed. I also tried an older version from 1826, but it still crashes at the step of selecting a folder. Personally, I think this might be due to an issue with the file manager of the cloud phone. I hope you can provide a new solution or idea.

**Comment by kyon1995** [comment]
> My situation is similar to his, with the only difference being that my system version is Android 10. I tried installing the system file manager you provided, but it showed that the installation was not completed. I also tried an older version from 1826, but it still crashes at the step of selecting a folder. Personally, I think this might be due to an issue with the file manager of the cloud phone. I hope you can provide a new solution or idea.

I found an alternative, I installed clone apps like vmos etc. but not vmos (I will put the PlayStore link below), when you have installed the application, you activate the play service in the VM settings, then in the VM you install FGA via PlayStore, and open it following the instructions, after that play as usual when you use FGA.
some time maybe you will find PlayStore service error blah blah blah .. but tapping ignore.
hope this helps for those of you who use Redfingger.
if you use LDcloud/LTcloud/UGphone you don't need to install VM in it, I've tried it, only Redfingger needs to be tricked with VM.

hope this helps.
VM link: https://play.google.com/store/apps/details?id=com.clone.android.dual.space

(vmos, virtual space, f1, 8x, cannot be installed in Redfingger, only Virtual Master can be installed in it)

**Comment by jcdeoferio** [comment]
Hi,

Any reason why I was tagged? I don't think I've commented in here or in the previous similar tickets.

**Comment by kyon1995** [comment]
> Hi,
> 
> Any reason why I was tagged? I don't think I've commented in here or in the previous similar tickets.

my bad.

**Comment by vybze** [comment]
Someone was able to solve their issue with this app https://m.apkpure.com/documentsui/com.google.android.documentsui
